kind: pipeline
type: docker
name: generate

steps:

- name: bundle
  image: trotttrotttrott/swagger-cli:4.0.4
  commands:
  - make bundle

- name: generate
  image: golang:1.14.6-alpine3.12
  commands:
  - go run . 7.0 jsonnet

- name: push
  image: alpine/git:v2.26.2
  environment:
    DEPLOY_KEY:
      from_secret: github_deploy_key
    GIT_COMMITTER_EMAIL: 69285523+bottbottbott@users.noreply.github.com
    GIT_COMMITTER_NAME: bottbottbott
  commands:
  - git add -f .
  - git commit -m '[drone] bundled specs and generated libraries'
  - mkdir -p /root/.ssh
  - echo "$DEPLOY_KEY" > /root/.ssh/id_rsa
  - chmod 600 /root/.ssh/id_rsa
  - touch /root/.ssh/known_hosts
  - chmod 600 /root/.ssh/known_hosts
  - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
  - git push -f git@github.com:trotttrotttrott/dashboard-spec HEAD:_gen

trigger:
  branch:
  - master
