fieldConfig:
  type: object
  properties:
    defaults:
      $ref: '#/defaults'
    overrides:
      type: array
      items:
        $ref: '#/override'

defaults:
  type: object
  properties:
    links:
      type: array
      items:
        $ref: 'link.yml#/link'
    mappings:
      type: array
      items:
        $ref: '#/mapping'
    max:
      type: integer
      default: 0
    min:
      type: integer
      default: 0
    thresholds:
      type: array
      items:
        $ref: '#/threshold'
    unit:
      type: string
      default: short

mapping:
  type: object
  properties:
    id:
      type: integer
    from:
      type: string
    operator:
      type: string
    to:
      type: string
    text:
      type: string
    type:
      type: integer
    value:
      type: string

override:
  type: object
  properties:
    matcher:
      type: oject
      properties:
        id:
          type: string
        options:
          type: string
    properties:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          value:
            type: integer

threshold:
  type: object
  properties:
    mode:
      type: string
      default: absolute
    steps:
      type: array
      items:
        type: object
        properties:
          color:
            type: string
          value:
            type: integer
