openapi: 3.0.3

info:
  title: Grafana Dashboard Spec
  version: '7.0'

paths: {}

components:
  schemas:
    DataSource:
      type: object
      properties:
        Prometheus:
          $ref: 'datasources/Prometheus.yml#/Prometheus'
    Panel:
      type: object
      properties:
        Gauge:
          $ref: 'panels/Gauge.yml#/Gauge'
        Stat:
          $ref: 'panels/Stat.yml#/Stat'
        Table:
          $ref: 'panels/Table.yml#/Table'
