openapi: 3.0.3

info:
  title: Grafana Dashboard Spec
  version: '7.0'

paths: {}

components:
  schemas:
    Dashboard:
      $ref: 'Dashboard.yml#/Dashboard'
    Panel:
      type: object
      properties:
        Gauge:
          $ref: 'panels/Gauge.yml#/Gauge'
        Graph:
          $ref: 'panels/Graph.yml#/Graph'
        Stat:
          $ref: 'panels/Stat.yml#/Stat'
        Table:
          $ref: 'panels/Table.yml#/Table'
    Target:
      type: object
      properties:
        Prometheus:
          $ref: 'targets/Prometheus.yml#/Prometheus'
    Template:
      type: object
      properties:
        Query:
          $ref: 'templates/Query.yml#/Query'
