Prometheus:
  type: object
  required:
    - expr
  properties:
    datasource:
      type: string
      default: default
    expr:
      type: string
    format:
      type: string
      default: time_series
    interval:
      type: string
    legendFormat:
      type: string
    refId:
      type: string
      readOnly: true
